# Generated by Django 4.2.3 on 2023-08-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goer',
            old_name='club',
            new_name='event',
        ),
    ]
