# Generated by Django 4.2.3 on 2023-08-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_club_goer_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventLink',
            field=models.CharField(default='link.com', max_length=100, verbose_name='Event Link'),
        ),
    ]
