"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
# Served in production from STATIC_ROOT after: python manage.py collectstatic --noinput
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'client', 'css'),
    os.path.join(BASE_DIR, 'client', 'js'),
    os.path.join(BASE_DIR, 'client', 'images'),
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# On PythonAnywhere, set DJANGO_SECRET_KEY in the WSGI config file (do not commit real secrets).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-*5pl%2a!bj401=r0jp)w0(hep)@0$ra3r@kr5hhm9(k8301!)$',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=false on the host (e.g. in WSGI file before loading the app).
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Comma-separated list, e.g. DJANGO_ALLOWED_HOSTS=yourname.pythonanywhere.com
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if h.strip()
]

# HTTPS on PythonAnywhere (and similar): set in WSGI, e.g.
# DJANGO_CSRF_TRUSTED_ORIGINS=https://yourname.pythonanywhere.com
_csrf_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in _csrf_origins.split(',') if o.strip()
]

# Trust X-Forwarded-Proto when DEBUG is off (reverse proxy / PA).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Set DJANGO_USE_WHITENOISE=false in WSGI if static files are served only via the Web tab mapping
# (helps isolate ImportError / misconfigured venv). Default: on.
_USE_WHITENOISE = os.environ.get('DJANGO_USE_WHITENOISE', 'true').lower() in (
    '1',
    'true',
    'yes',
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.clubs',
    'myapp',
    'base',
    'events',
    'careers',
    'experientiallearning',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    *(
        ('whitenoise.middleware.WhiteNoiseMiddleware',)
        if _USE_WHITENOISE
        else ()
    ),
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'client', 'html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'static'
CSV_FILE_DIR = os.path.join(BASE_DIR, 'static', 'csv')

# Serve /static/ in production (DEBUG=False) without relying only on PythonAnywhere nginx mapping.
if not DEBUG and _USE_WHITENOISE:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User models

AUTH_USER_MODEL = 'myapp.CustomUser'
LOGIN_URL = '/signin/'
LOGIN_REDIRECT_URL = '/'