# Generated by Django 4.2.3 on 2023-08-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_club_goer_event'),
        ('myapp', '0010_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='events',
            field=models.ManyToManyField(related_name='attendee', to='events.event'),
        ),
    ]
