# Generated by Django 4.2.3 on 2023-08-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAndSociety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Individual and Society',
            },
        ),
        migrations.CreateModel(
            name='ProgramElectives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Program Electives',
            },
        ),
        migrations.CreateModel(
            name='USExperienceInItsDiversity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'US Experience In ItsDiversity',
            },
        ),
        migrations.CreateModel(
            name='WorldCulturesAndGlobalIssues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'World Cultures And GlobalIssues',
            },
        ),
    ]
