# Generated by Django 5.1.2 on 2026-04-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_elective_course_tables_if_missing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_key', models.SlugField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['series_key', 'year'],
                'constraints': [models.UniqueConstraint(fields=('series_key', 'year'), name='department_metric_series_year_uniq')],
            },
        ),
    ]
